Update android12-5.10-clang-20.yml

diff --git a/.github/workflows/android12-5.10-clang-20.yml b/.github/workflows/android12-5.10-clang-20.yml
--- a/.github/workflows/android12-5.10-clang-20.yml
+++ b/.github/workflows/android12-5.10-clang-20.yml
@@ -22,14 +22,14 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - name: check-patches-apply.py
-      run: python3 scripts/check-patches-apply.py --patches-dir patches/android12-5.10 --repo https://android.googlesource.com/kernel/common.git --ref android12-5.10
+      run: python3 scripts/check-patches-apply.py --patches-dir patches/android12-5.10 --repo https://github.com/Guxin12/android_kernel_xiaomi_marble.git --ref android12-5.10  # 替换为带.git的地址
   check_cache:
     name: Check Cache
     runs-on: ubuntu-latest
     container: tuxmake/x86_64_korg-clang-20
     needs: check_patches
     env:
-      GIT_REPO: https://android.googlesource.com/kernel/common.git
+      GIT_REPO: https://github.com/Guxin12/android_kernel_xiaomi_marble.git  # 替换为带.git的地址
       GIT_REF: android12-5.10
     outputs:
       output: ${{ steps.step2.outputs.output }}
@@ -42,9 +42,6 @@ jobs:
       id: step1
       continue-on-error: true
       run: . venv/bin/activate && python caching/check.py -w '${{ github.workflow }}' -g ${{ secrets.REPO_SCOPED_PAT }} -r ${{ env.GIT_REF }} -o ${{ env.GIT_REPO }}
-    - name: Save exit code to GITHUB_OUTPUT
-      id: step2
-      run: echo "output=${{ steps.step1.outcome }}" >> "$GITHUB_OUTPUT" && echo "status=$CACHE_PASS" >> "$GITHUB_OUTPUT"
   kick_tuxsuite_defconfigs:
     name: TuxSuite (defconfigs)
     runs-on: ubuntu-latest
@@ -67,7 +64,7 @@ jobs:
       if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
     - name: tuxsuite
       if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
-      run: tuxsuite plan --git-repo https://android.googlesource.com/kernel/common.git --git-ref android12-5.10 --job-name defconfigs --json-out builds.json --patch-series patches/android12-5.10 tuxsuite/android12-5.10-clang-20.tux.yml || true
+      run: tuxsuite plan --git-repo https://github.com/Guxin12/android_kernel_xiaomi_marble.git --git-ref android12-5.10 --job-name defconfigs --json-out builds.json --patch-series patches/android12-5.10 tuxsuite/android12-5.10-clang-20.tux.yml || true  # 替换为带.git的地址
     - name: Update Cache Build Status
       if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
       run: python caching/update.py
@@ -88,6 +85,49 @@ jobs:
         path: boot-utils.json
         name: boot_utils_json_defconfigs
         if-no-files-found: error
+  kick_tuxsuite_allconfigs:
+    name: TuxSuite (allconfigs)
+    runs-on: ubuntu-latest
+    container: tuxsuite/tuxsuite
+    needs:
+    - check_cache
+    - check_patches
+    env:
+      TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}
+      REPO_SCOPED_PAT: ${{ secrets.REPO_SCOPED_PAT }}
+    timeout-minutes: 480
+    steps:
+    - name: Checking Cache Pass
+      if: ${{ needs.check_cache.outputs.output == 'success' && github.event_name != 'workflow_dispatch' && needs.check_cache.outputs.status == 'pass' }}
+      run: echo 'Cache HIT on previously PASSED build. Passing this build to avoid redundant work.' && exit 0
+    - name: Checking Cache Fail
+      if: ${{ needs.check_cache.outputs.output == 'success' && github.event_name != 'workflow_dispatch' && needs.check_cache.outputs.status == 'fail' }}
+      run: echo 'Cache HIT on previously FAILED build. Failing this build to avoid redundant work.' && exit 1
+    - uses: actions/checkout@v4
+      if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
+    - name: tuxsuite
+      if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
+      run: tuxsuite plan --git-repo https://github.com/Guxin12/android_kernel_xiaomi_marble.git --git-ref android12-5.10 --job-name allconfigs --json-out builds.json --patch-series patches/android12-5.10 tuxsuite/android12-5.10-clang-20.tux.yml || true  # 替换为带.git的地址
+    - name: Update Cache Build Status
+      if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
+      run: python caching/update.py
+    - name: save builds.json
+      if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
+      uses: actions/upload-artifact@v4
+      with:
+        path: builds.json
+        name: output_artifact_allconfigs
+        if-no-files-found: error
+    - name: generate boot-utils.json
+      if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
+      run: python3 scripts/generate-boot-utils-json.py ${{ secrets.GITHUB_TOKEN }}
+    - name: save boot-utils.json
+      if: ${{ needs.check_cache.outputs.output == 'failure' || github.event_name == 'workflow_dispatch' }}
+      uses: actions/upload-artifact@v4
+      with:
+        path: boot-utils.json
+        name: boot_utils_json_allconfigs
+        if-no-files-found: error  
   _1496dc163fc32d9c10262045592fb5f9:
     runs-on: ubuntu-latest
     needs:
